spring:
  application:
    name: expense
  datasource:
    url: jdbc:mysql://localhost:3306/personal_budget_tracker
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8763

# JWT Specific Configuration
jwt:
  secret: Jf94nA8snf94nA8snf94nA8snf94nA8s
  access-token-expiration: 3600000
  refresh-token-expiration: 2592000000
