spring:
  application: name:personal_budget_tracker
  datasource:
    url: jdbc:mysql://localhost:3306/budget_tracker
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    static-path-pattern: /static/**
