spring:
  application: name:personal_budget_tracker
  datasource:
    url: jdbc:mysql://localhost:3306/personal_budget_tracker
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    static-path-pattern: /static/**
