spring:
  application:
    name: personal_budget_tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/budget_tracker
    username: postgres
    password: "621952"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update 
    show-sql: true

  mvc:
    static-path-pattern: /static/**
