spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/personal_budget_tracker
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

# JWT Specific Configuration
jwt:
  secret: Jf94nA8snf94nA8snf94nA8snf94nA8s
  access-token-expiration: 2592000000
  refresh-token-expiration: 2592000000

server:
  port: 8764

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com:
      example: INFO
  file:
    name: logs/auth.log
    path: logs
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
