spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:5173'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - '*'
            allowCredentials: true

server:
  port: 8765

logging:
  level:
    com:
      example: INFO
  file:
    name: logs/gateway.log
    path: logs
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
